# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]


jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-latest, ubuntu-latest, windows-latest ]

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Install golang
        uses: actions/setup-go@master
        with:
          go-version: 1.15
        id: go

      - name: Log Go version
        run: |
          go version

      - name: Test Go Application
          run: |
            go version
            go text zhihu-hot-questions/test