# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]


jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-latest, ubuntu-latest, windows-latest ]

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Install golang
        uses: actions/setup-go@master
        with:
          go-version: 1.15
        id: go

      - name: Test Go Application
        run: |
          go version
          go test zhihu-hot-questions/test

      - name: Complete App
        run: |
          git config --local user.email "1191430240@qq.com"
          git config --local user.name "ToWeLong"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          go mod download
          go run app.go
          git add .
          git commit -m "update by github action"
          git push
